doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            test_status: App\DoctrineType\TestStatusType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                CONTAINS: 'OpsWay\Doctrine\ORM\Query\AST\Functions\Contains'
                CONTAINED: 'OpsWay\Doctrine\ORM\Query\AST\Functions\Contained'
                GET_JSON_FIELD: 'OpsWay\Doctrine\ORM\Query\AST\Functions\GetJsonField'
                GET_JSON_FIELD_BY_KEY: 'OpsWay\Doctrine\ORM\Query\AST\Functions\GetJsonFieldByKey'
                GET_JSON_OBJECT: 'OpsWay\Doctrine\ORM\Query\AST\Functions\GetJsonObject'
                GET_JSON_OBJECT_TEXT: 'OpsWay\Doctrine\ORM\Query\AST\Functions\GetJsonObjectText'
                ANY_OP: 'OpsWay\Doctrine\ORM\Query\AST\Functions\Any'
                ALL_OP: 'OpsWay\Doctrine\ORM\Query\AST\Functions\All'
                ARR: 'OpsWay\Doctrine\ORM\Query\AST\Functions\Arr'
                ARR_AGGREGATE: 'OpsWay\Doctrine\ORM\Query\AST\Functions\ArrayAggregate'
                ARR_APPEND: 'OpsWay\Doctrine\ORM\Query\AST\Functions\ArrayAppend'
                ARR_REPLACE: 'OpsWay\Doctrine\ORM\Query\AST\Functions\ArrayReplace'
                REGEXP_REPLACE: 'OpsWay\Doctrine\ORM\Query\AST\Functions\RegexpReplace'
                ARR_REMOVE: 'OpsWay\Doctrine\ORM\Query\AST\Functions\ArrayRemove'
                ARR_CONTAINS: 'OpsWay\Doctrine\ORM\Query\AST\Functions\ArrayContains'
                TO_TSQUERY: 'OpsWay\Doctrine\ORM\Query\AST\Functions\ToTsquery'
                TO_TSVECTOR: 'OpsWay\Doctrine\ORM\Query\AST\Functions\ToTsvector'
                TS_CONCAT_OP: 'OpsWay\Doctrine\ORM\Query\AST\Functions\TsConcat'
                TS_MATCH_OP: 'OpsWay\Doctrine\ORM\Query\AST\Functions\TsMatch'
                UNNEST: 'OpsWay\Doctrine\ORM\Query\AST\Functions\Unnest'
                JSON_AGG: 'OpsWay\Doctrine\ORM\Query\AST\Functions\JsonAgg'
                JSONB_ARRAY_ELEM_TEXT: 'OpsWay\Doctrine\ORM\Query\AST\Functions\JsonbArrayElementsText'


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
